channels:
  - conda-forge
  - intel
  - defaults
dependencies:
  - python=3.10
  - pip
  - graphviz
  - intel::mpi4py
  - pip:
    - black
    - flake8
    - nbqa
    - pdbpp
    - numpy
    - scipy
    - scikit-learn
    - matplotlib
    - joblib
    - dask[complete]
    - dask-jobqueue
    - dask-ml
    - dask-mpi
    - graphviz
    - torch
    - skorch
    - --extra-index-url https://download.pytorch.org/whl/cu116
